-- If not exists
CREATE USER [AppFabric] FOR LOGIN [AppFabric];
GO


GRANT SELECT TO [AppFabric];
GRANT ALTER ANY EXTERNAL MIRROR TO [AppFabric];
GRANT VIEW DATABASE PERFORMANCE STATE TO [AppFabric];
GRANT VIEW DATABASE SECURITY STATE TO [AppFabric];
GO
